### ISSUE TITLE
Nutrient Vat takes up a 1x2 space and is unrotatable

### ISSUE THREAD

**Issue by cnalty** [juanosarg/GeneticRim#8]
The Nutrient Vat appears as though it should have a 1x1 placement space and extends upwards (such as a large sculpture), but has a 1x2 placement space.

If this 1x2 placement space is intended, the Nutrient Vat does not have the ability to be rotated, unlike all other unsymmetrical objects in Rimworld

![Screenshot from 2020-04-16 14-17-35](https://user-images.githubusercontent.com/37752899/79491893-20a6cb00-7fed-11ea-984b-c33933e31e74.png)

**Comment by juanosarg** [comment]
This is intentional, though. I wanted it to be tall, and RW does not have support for tall buildings. Instead of having it cause graphical glitches like the trees in Alpha Biomes, I opted to have it occupy the space directly behind it.

Rotation would be absurd, since it would look mostly the same, and still occupy that space behind it
